config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'books/index', to: "books#index"
  get 'books/search', to: "books#search"
  get 'books/new', to: "books#new"
  post 'books/new', to: "review1s#create"
  post 'books/create', to: "books#create"
  get 'books/index', to: "books#index"
  
  get 'review1s/book_review1s', to: "review1s#book_review1s"
  get 'review1s/personal_review1s', to: "review1s#personal_review1s"
  get 'review1s/my_review1s', to: "review1s#my_review1s"
  
  delete 'review1s/destroy:id', to: 'review1s#destroy'
  
  get 'microposts/followings', to: 'microposts#followings'
  
  resources :users, only: [:index, :show, :create]do
    member do
      get :followings
      get :followers
      get :likes
      get :review1s
    end
  end
    resources :review1s,only: [:index, :create, :destroy, :edit, :update]
    resources :relationships, only: [:create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
   def index
    if logged_in?
      @user = User.find(current_user.id)
      $current_user_review1s=Review1.where(user_id: current_user.id)
      @pagy, $current_user_review1s = pagy($current_user_review1s.order(id: :ASC), items: 15)
    end
  end
end

app/views/toppages/index.html.erb
<%= stylesheet_link_tag "all", :media => "all" %>
<% if logged_in? %>
<body>
<div class="row">
  <aside class="col-sm-4">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title"><%= @user.name %></h3>
      </div>
      <div class="card-body">
        <img class="rounded img-fluid" src="<%= gravatar_url(@user, { size: 500 }) %>" alt="">
      </div>
    </div>
    <%= render 'relationships/follow_button', user: @user %>
  </aside>
  <div class="col-sm-8">
    <ul class="nav nav-tabs nav-justified mb-3">
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link">Likes  <span class="badge bg-secondary"><%= $count_lovings %></span></a></li>
      <li class="nav-item"><a href="<%= review1s_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(review1s_user_path(@user)) %>">Reviews<span class="badge bg-secondary"><%= $count_user_review1s %></span></a></li>
      <li class="nav-item"><a href="<%= followings_user_path(@user) %>" class="nav-link">Followings<span class="badge bg-secondary"><%= $count_followings %></span></a></li>
      <li class="nav-item"><a href="<%= followers_user_path(@user) %>" class="nav-link">Followers<span class="badge bg-secondary"><%= $count_followers %></span></a></li>
    </ul>
    <%= render 'review1s/my_review1s', review1s: $curent_user_review1s %>
  </div>
</div>
</body>
<% else %>
<body>
  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Welcome to the myfavorites</h1>
      <%= link_to 'Sign up now!', signup_path, class: 'btn btn-lg btn-primary' %>
    </div>
  </div>
</body>
<% end %>