config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'toppages#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  get 'books/index', to: "books#index"
  get 'books/search', to: "books#search"
  get 'books/new', to: "books#new"
  post 'books/new', to: "review1s#create"
  post 'books/create', to: "books#create"
  get 'books/index', to: "books#index"
  
  get 'review1s/book_review1s', to: "review1s#book_review1s"
  get 'review1s/personal_review1s', to: "review1s#personal_review1s"
  get 'review1s/my_review1s', to: "review1s#my_review1s"
  
  delete 'review1s/destroy:id', to: 'review1s#destroy'
  
  get 'microposts/followings', to: 'microposts#followings'
  
  resources :users, only: [:index, :show, :create]do
    member do
      get :followings
      get :followers
      get :likes
      get :review1s
    end
  end
    resources :review1s,only: [:index, :create, :destroy, :edit, :update]
    resources :relationships, only: [:create, :destroy]
    resources :favorites, only: [:index, :create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand" href="/">My favorites</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
  <% if logged_in? %>
    <div class="btn-group">
      <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%='book review' %></button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li class="dropdown-item"><%= link_to '書籍検索', books_search_path, class: 'nav-link' %></li>
        <li class="dropdown-divider"></li>
        <li class="dropdown-item"><%= link_to '自分の投稿したブックレビュー一覧', review1s_my_review1s_path, class: 'nav-link' %></li>
        <li class="dropdown-divider"></li>
        <li class="dropdown-item"><%= link_to 'みんなの投稿したブックレビュー一覧', books_index_path, class: 'nav-link' %></li>
      </ul>
      <button type="button" class="btn btn-dark dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"><%= current_user.name %></button>
      <ul class="dropdown-menu dropdown-menu-end">
        <li class="dropdown-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
        <li class="dropdown-divider"></li>
        <li class="dropdown-item"><%= link_to 'My profile', user_path(current_user), class: 'nav-link' %></li>
        <li class="dropdown-divider"></li>
        <li class="dropdown-item"><%= link_to 'Logout', logout_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    </div>
  <% else %>
    <ul class="navbar-nav">
      <li class="nav-item"><%= link_to 'ユーザー新規登録', signup_path, class: 'nav-link' %></li>
      <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
    </ul>
  <% end %>
</div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>My favorites</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>

  <body data-turbolinks="false">
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>